export const defaultPrices = {
  Potato: 35,
  Cotton: 200,
  Corn: 133,
  Wheat: 66,
  Apple: 200,
  Carrot: 33,
  Grape: 118,
  Blueberry: 30,
  Cabbage: 93,
  Pepper: 139,
  Cherries: 300,
  Orange: 350,
  Onion: 200,
  Strawberry: 50,
  Beans: 60,
  Banana: 529,
  Pumpkin: 433,
  Watermelon: 530,
  Pea: 92,
  Moonberry: 342,
  Garlic: 770,
  Acorn: 4000,
  Brocolli: 2000,
  Sunberry: 1000,
};

export const landCapacities = {
  small: 28,
  medium: 79,
  large: 151,
};

// Capacidades para árvores (que ocupam mais espaço)
export const treeLandCapacities = {
  small: 10,
  medium: 26,
  large: 48,
};

export interface Farm {
  name: string;
  image: string;
  xp: number;
  isTree: boolean;
  minYield: number;
  maxYield: number;
  harvestTimeHours: number;
  effort: number;
  cost: number;
  level: number;
}

export const farms: Farm[] = [
  {
    name: "Potato",
    image: "potato.png",
    xp: 80,
    isTree: false,
    minYield: 2,
    maxYield: 4,
    harvestTimeHours: 1,
    effort: 2,
    cost: 36,
    level: 1,
  },
  {
    name: "Cotton",
    image: "cotton.png",
    xp: 1378,
    isTree: true,
    minYield: 4,
    maxYield: 8,
    harvestTimeHours: 4.5,
    effort: 90,
    cost: 1320,
    level: 1,
  },
  {
    name: "Corn",
    image: "corn.png",
    xp: 1034,
    isTree: false,
    minYield: 6,
    maxYield: 9,
    harvestTimeHours: 15,
    effort: 37,
    cost: 564,
    level: 3,
  },
  {
    name: "Wheat",
    image: "wheat.png",
    xp: 452,
    isTree: false,
    minYield: 3,
    maxYield: 9,
    harvestTimeHours: 6,
    effort: 15,
    cost: 216,
    level: 5,
  },
  {
    name: "Apple",
    image: "apple.png",
    xp: 2226,
    isTree: true,
    minYield: 3,
    maxYield: 6,
    harvestTimeHours: 7.5,
    effort: 150,
    cost: 2220,
    level: 7,
  },
  {
    name: "Carrot",
    image: "carrot.png",
    xp: 158,
    isTree: false,
    minYield: 2,
    maxYield: 4,
    harvestTimeHours: 2,
    effort: 5,
    cost: 84,
    level: 10,
  },
  {
    name: "Grape",
    image: "grape.png",
    xp: 452,
    effort: 15,
    cost: 216,
    harvestTimeHours: 6,
    minYield: 2,
    maxYield: 4,
    isTree: false,
    level: 15,
  },

  {
    name: "Blueberry",
    image: "blueberry.png",
    xp: 452,
    isTree: false,
    minYield: 9,
    maxYield: 15,
    harvestTimeHours: 6,
    effort: 15,
    cost: 216,
    level: 17,
  },
  {
    name: "Cabbage",
    image: "cabbage.png",
    xp: 452,
    isTree: false,
    minYield: 2,
    maxYield: 4,
    harvestTimeHours: 6,
    effort: 15,
    cost: 216,
    level: 20,
  },
  {
    name: "Pepper",
    image: "pepper.png",
    xp: 1714,
    isTree: false,
    minYield: 9,
    maxYield: 15,
    harvestTimeHours: 28.5,
    effort: 71,
    cost: 1080,
    level: 21,
  },
  {
    name: "Cherries",
    image: "cherries.png",
    xp: 5448,
    isTree: true,
    minYield: 6,
    maxYield: 12,
    harvestTimeHours: 21,
    effort: 420,
    cost: 6300,
    level: 21,
  },
  {
    name: "Orange",
    image: "orange.png",
    xp: 4132,
    isTree: true,
    minYield: 3,
    maxYield: 6,
    harvestTimeHours: 15,
    effort: 300,
    cost: 4500,
    level: 22,
  },
  {
    name: "Onion",
    image: "onion.png",
    xp: 658,
    isTree: false,
    minYield: 3,
    maxYield: 6,
    harvestTimeHours: 9,
    effort: 22,
    cost: 336,
    level: 25,
  },
  {
    name: "Strawberry",
    image: "strawberry.png",
    xp: 558,
    isTree: false,
    minYield: 6,
    maxYield: 12,
    harvestTimeHours: 7.5,
    effort: 18,
    cost: 288,
    level: 27,
  },
  {
    name: "Beans",
    image: "beans.png",
    xp: 1034,
    isTree: false,
    minYield: 9,
    maxYield: 15,
    harvestTimeHours: 15,
    effort: 37,
    cost: 564,
    level: 30,
  },
  {
    name: "Banana",
    image: "banana.png",
    xp: 6042,
    isTree: true,
    minYield: 6,
    maxYield: 12,
    harvestTimeHours: 24,
    effort: 480,
    cost: 7200,
    level: 32,
  },
  {
    name: "Pumpkin",
    image: "pumpkin.png",
    xp: 1510,
    isTree: false,
    minYield: 2,
    maxYield: 4,
    harvestTimeHours: 24,
    effort: 60,
    cost: 900,
    level: 35,
  },
  {
    name: "Watermelon",
    image: "watermelon.png",
    xp: 1778,
    isTree: false,
    minYield: 2,
    maxYield: 4,
    harvestTimeHours: 30,
    effort: 75,
    cost: 1080,
    level: 37,
  },
  {
    name: "Pea",
    image: "pea.png",
    xp: 1284,
    isTree: false,
    minYield: 9,
    maxYield: 15,
    harvestTimeHours: 19.5,
    effort: 48,
    cost: 720,
    level: 40,
  },
  {
    name: "Moonberry",
    image: "moonberry.png",
    xp: 1362,
    isTree: false,
    minYield: 3,
    maxYield: 9,
    harvestTimeHours: 21,
    effort: 52,
    cost: 792,
    level: 42,
  },
  {
    name: "Garlic",
    image: "garlic.png",
    xp: 1120,
    isTree: false,
    minYield: 6,
    maxYield: 12,
    harvestTimeHours: 16.5,
    effort: 41,
    cost: 600,
    level: 45,
  },
  {
    name: "Acorn",
    image: "acorn.png",
    xp: 9504,
    isTree: true,
    minYield: 6,
    maxYield: 12,
    harvestTimeHours: 48,
    effort: 960,
    cost: 14400,
    level: 47,
  },
  {
    name: "Brocolli",
    image: "brocolli.png",
    xp: 1034,
    isTree: false,
    minYield: 3,
    maxYield: 6,
    harvestTimeHours: 15,
    effort: 37,
    cost: 564,
    level: 50,
  },
  {
    name: "Sunberry",
    image: "sunberry.png",
    xp: 1778,
    isTree: false,
    minYield: 3,
    maxYield: 9,
    harvestTimeHours: 30,
    effort: 75,
    cost: 1080,
    level: 52,
  },
];
