export interface Farm {
  name: string;
  image: string;
  xp: number;
  isTree: boolean;
  minYield: number;
  maxYield: number;
  harvestTimeHours: number;
  effort: number;
  cost: number;
  level?: number;
}

export const farms: Farm[] = [
  {
    name: "Potato",
    image: "potato.png",
    xp: 80,
    isTree: false,
    minYield: 2,
    maxYield: 4,
    harvestTimeHours: 1,
    effort: 2,
    cost: 36,
  },
  {
    name: "Cotton Tree",
    image: "cotton.png",
    xp: 1378,
    isTree: true,
    minYield: 4,
    maxYield: 8,
    harvestTimeHours: 4.5,
    effort: 90,
    cost: 1320,
  },
  {
    name: "Corn",
    image: "corn.png",
    xp: 1034,
    isTree: false,
    minYield: 6,
    maxYield: 9,
    harvestTimeHours: 15,
    effort: 37,
    cost: 564,
  },
  {
    name: "Wheat",
    image: "wheat.png",
    xp: 452,
    isTree: false,
    minYield: 3,
    maxYield: 9,
    harvestTimeHours: 6,
    effort: 15,
    cost: 216,
  },
  {
    name: "Apple Tree",
    image: "apple.png",
    xp: 2226,
    isTree: true,
    minYield: 3,
    maxYield: 6,
    harvestTimeHours: 7.5,
    effort: 150,
    cost: 2220,
  },
  {
    name: "Carrot",
    image: "carrot.png",
    xp: 158,
    isTree: false,
    minYield: 2,
    maxYield: 4,
    harvestTimeHours: 2,
    effort: 5,
    cost: 84,
  },
  {
    name: "Grape",
    image: "grape.png",
    xp: 452,
    effort: 15,
    cost: 216,
    harvestTimeHours: 6,
    minYield: 2,
    maxYield: 4,
    isTree: false,
  },

  {
    name: "Blueberry",
    image: "blueberry.png",
    xp: 452,
    isTree: false,
    minYield: 9,
    maxYield: 15,
    harvestTimeHours: 6,
    effort: 15,
    cost: 216,
  },
  {
    name: "Cabbage",
    image: "cabbage.png",
    xp: 452,
    isTree: false,
    minYield: 2,
    maxYield: 4,
    harvestTimeHours: 6,
    effort: 15,
    cost: 216,
  },
  {
    name: "Pepper",
    image: "pepper.png",
    xp: 1714,
    isTree: false,
    minYield: 9,
    maxYield: 15,
    harvestTimeHours: 28.5,
    effort: 71,
    cost: 1080,
  },
  {
    name: "Cherries",
    image: "cherries.png",
    xp: 5448,
    isTree: true,
    minYield: 6,
    maxYield: 12,
    harvestTimeHours: 21,
    effort: 420,
    cost: 6300,
  },
  {
    name: "Orange",
    image: "orange.png",
    xp: 4132,
    isTree: true,
    minYield: 3,
    maxYield: 6,
    harvestTimeHours: 15,
    effort: 300,
    cost: 4500,
  },
  {
    name: "Onion",
    image: "onion.png",
    xp: 658,
    isTree: false,
    minYield: 3,
    maxYield: 6,
    harvestTimeHours: 9,
    effort: 22,
    cost: 336,
  },
  {
    name: "Strawberry",
    image: "strawberry.png",
    xp: 558,
    isTree: false,
    minYield: 6,
    maxYield: 12,
    harvestTimeHours: 7.5,
    effort: 18,
    cost: 288,
  },
  {
    name: "Beans",
    image: "beans.png",
    xp: 1034,
    isTree: false,
    minYield: 9,
    maxYield: 15,
    harvestTimeHours: 15,
    effort: 37,
    cost: 564,
  },
  {
    name: "Banana",
    image: "banana.png",
    xp: 6042,
    isTree: true,
    minYield: 6,
    maxYield: 12,
    harvestTimeHours: 24,
    effort: 480,
    cost: 7200,
  },
  {
    name: "Pumpkin",
    image: "pumpkin.png",
    xp: 1510,
    isTree: false,
    minYield: 2,
    maxYield: 4,
    harvestTimeHours: 24,
    effort: 60,
    cost: 900,
  },
  {
    name: "Watermelon",
    image: "watermelon.png",
    xp: 1778,
    isTree: false,
    minYield: 2,
    maxYield: 4,
    harvestTimeHours: 30,
    effort: 75,
    cost: 1080,
  },
  {
    name: "Pea",
    image: "pea.png",
    xp: 1284,
    isTree: false,
    minYield: 9,
    maxYield: 15,
    harvestTimeHours: 19.5,
    effort: 48,
    cost: 720,
  },
  {
    name: "Moonberry",
    image: "moonberry.png",
    xp: 1362,
    isTree: false,
    minYield: 3,
    maxYield: 9,
    harvestTimeHours: 21,
    effort: 52,
    cost: 792,
  },
  {
    name: "Garlic",
    image: "garlic.png",
    xp: 1120,
    isTree: false,
    minYield: 6,
    maxYield: 12,
    harvestTimeHours: 16.5,
    effort: 41,
    cost: 600,
  },
  {
    name: "Acorn",
    image: "acorn.png",
    xp: 9504,
    isTree: true,
    minYield: 6,
    maxYield: 12,
    harvestTimeHours: 48,
    effort: 960,
    cost: 14400,
  },
  {
    name: "Brocolli",
    image: "brocolli.png",
    xp: 1034,
    isTree: false,
    minYield: 3,
    maxYield: 6,
    harvestTimeHours: 15,
    effort: 37,
    cost: 564,
  },
  {
    name: "Sunberry",
    image: "sunberry.png",
    xp: 1778,
    isTree: false,
    minYield: 3,
    maxYield: 9,
    harvestTimeHours: 30,
    effort: 75,
    cost: 1080,
  },
];
